version: '3'

services: 
    nexus:
        build:
            context: ./docker/nexus
        environment: 
            - NEXUS_PASSWORD=cvf,bo
        ports: 
            - 80:8081
        volumes:
            - ./docker/nexus/data:/nexus-data